name: CI/CD

on:
  push:
    branches: [ master ]
jobs:
    staging-deploy:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/master'
      steps:
      - uses: actions/checkout@v1
      - name: AWS Create Deploy
        uses: ItsKarma/aws-cli@v1.70.0
        env:
          AWS_ACCESS_KEY_ID: 123123123123
          AWS_SECRET_ACCESS_KEY: 12312313133
          AWS_DEFAULT_REGION: "us-east-1"
          COMMIT_ID: ${{env.GITHUB_SHA}}
        with:
          args: s3 ls s3://${{env.COMMIT_ID}}
